version: "3"
services:
  next:
    container_name: rabe-next
    build:
      dockerfile: ${DOCKERFILENAME:-./Dockerfile.prod}
      context: ./next
    env_file: .env
    restart: unless-stopped
    ports:
      - "${NEXT_PORT}:3000"

  directus:
    container_name: rabe-directus
    image: directus/directus:latest
    # build:
    #   context: ./directus
    ports:
      - ${BE_PORT}:8055
    volumes:
      - ./directus/database:/directus/database
      - ./directus/uploads:/directus/uploads
      - ./directus/extensions:/directus/extensions
    env_file: .env
    restart: unless-stopped

  DB:
    container_name: rabe-DB
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_HOST}
    volumes:
      - rabe-data:/var/lib/postgresql/data/ #using a volume
      #- ./data:/var/lib/postgresql/data/ # if you want to use a bind folder
    # ports:
    #   - '${DATABASE_PORT}:5432'
    # networks:
    #   - rabeNetwork

volumes:
  rabe-data:
# networks:
#   rabeNetwork:
#     name: rabeNetwork
#     driver: bridge
