version: '3'
services:
  strapi:
    container_name: rabe-strapi
    build:
      dockerfile: Dockerfile
      context: ./strapi
    image: strapi:latest
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./strapi/config:/opt/app/config
      - ./strapi/src:/opt/app/src
      - ./strapi/package.json:/opt/package.json
      - ./strapi/yarn.lock:/opt/yarn.lock
      - ./.env:/opt/app/.env
      - ./strapi/public/uploads:/opt/app/public/uploads
    ports:
      - '${STRAPI_PORT}:1337'
    networks:
      - strapi
    depends_on:
      - strapiDB
      
  strapiDB:
    container_name: rabe-strapiDB
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - strapi-data:/var/lib/postgresql/data/ #using a volume
      #- ./data:/var/lib/postgresql/data/ # if you want to use a bind folder

    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    networks:
      - strapi
      
  # strapiAdminer:
  #   container_name: strapiAdminer
  #   image: adminer
  #   restart: unless-stopped
  #   ports:
  #     - '9090:8080'
  #   environment:
  #     - ADMINER_DEFAULT_SERVER=strapiDB
  #   networks:
  #     - strapi
  #   depends_on:
  #     - strapiDB

volumes:
  strapi-data:

networks:
  strapi:
    name: Strapi
    driver: bridge
