version: "3"
services:
  next:
    container_name: rabe-next
    build:
      dockerfile: ${DOCKERFILENAME:-./Dockerfile.prod}
      context: ./next
    env_file: .env
    restart: unless-stopped
    ports:
      - "${NEXT_PORT}:3000"
    depends_on:
      directus:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider ${NEXT_PUBLIC_FE_URL}/api/healthcheck || exit 1
      start_period: 15s
      interval: 15s
      timeout: 15s
      retries: 3

  directus:
    container_name: rabe-directus
    build:
      dockerfile: ./Dockerfile
      context: ./directus
    ports:
      - ${BE_PORT}:8055
    volumes:
      - ./directus/database:/directus/database
      - ./directus/uploads:/directus/uploads
      - ./directus/extensions:/directus/extensions
    env_file: .env
    restart: unless-stopped
    healthcheck:
      test: wget --no-verbose --tries=1 --spider ${NEXT_PUBLIC_BE_URL}/server/health || exit 1
      start_period: 15s
      interval: 15s
      timeout: 15s
      retries: 3
