version: "3"
services:
  telegram-notifier:
    image: lorcas/docker-telegram-notifier:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # for local instance
    environment:
      TELEGRAM_NOTIFIER_BOT_TOKEN: 7148634886:AAEyT5wkMCdWCESViNJ7p-OiQCOIF4t7J3M
      TELEGRAM_NOTIFIER_CHAT_ID: -4746521148

  next:
    container_name: rabe-next
    build:
      dockerfile: ${DOCKERFILENAME:-./Dockerfile.prod}
      context: ./next
    env_file: .env
    restart: unless-stopped
    ports:
      - "${NEXT_PORT}:3000"
    depends_on:
      directus:
        condition: service_healthy

  # cache: # check here: https://docs.directus.io/self-hosted/docker-guide.html#example-docker-compose
  #   image: redis:6
  #   healthcheck:
  #     test: ["CMD-SHELL", "[ $$(redis-cli ping) = 'PONG' ]"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #     start_interval: 5s
  #     start_period: 30s

  directus:
    container_name: rabe-directus
    build:
      dockerfile: ./Dockerfile
      context: ./directus
    ports:
      - ${BE_PORT}:8055
    volumes:
      - ./directus/database:/directus/database
      - ./directus/uploads:/directus/uploads
      - ./directus/extensions:/directus/extensions
      - ./directus/migrations:/directus/migrations
    env_file: .env
    restart: unless-stopped
