version: "3"
services:
  next:
    container_name: rabe-next
    build:
      dockerfile: ${DOCKERFILENAME:-./Dockerfile.prod}
      context: ./next
    env_file: .env
    restart: unless-stopped
    ports:
      - "${NEXT_PORT}:3000"

  directus:
    container_name: rabe-directus
    build:
      dockerfile: ./Dockerfile
      context: ./directus
    ports:
      - ${BE_PORT}:8055
    volumes:
      - ./directus/database:/directus/database
      - ./directus/uploads:/directus/uploads
      - ./directus/extensions:/directus/extensions
    env_file: .env
    restart: unless-stopped
